### ISSUE TITLE
Question: unreachable code in ES5.js

### ISSUE THREAD

**Issue by Xotic750** [ljharb/es-to-primitive#2]
In ES5.js, the following line is unreachable.

https://github.com/ljharb/es-to-primitive/blob/master/es5.js#L47

Which in turn, it seems that `ES5internalSlots` is never called.

https://github.com/ljharb/es-to-primitive/blob/master/es5.js#L10

And `IsCallable` is loaded but never used.

https://github.com/ljharb/es-to-primitive/blob/master/es5.js#L7

Is this intentional?

**Comment by ljharb** [comment]
Hmm, good question. It's not intentional.

In the spec, ToPrimitive points to https://es5.github.io/#x8.12.8, so it actually appears like lines https://github.com/ljharb/es-to-primitive/blob/master/es5.js#L40-L46 should be deleted.

However, it's also possible that using `String` and `Number` like I'm doing bypasses the need to implement `[[DefaultValue]]`, which would mean I could delete it entirely, along with `isCallable`.

**Comment by ljharb** [comment]
Turns out I had a bunch of incorrect stuff in my ES5 tests. Fixing it, and removing https://github.com/ljharb/es-to-primitive/blob/master/es5.js#L40-L46, plus one minor fix in https://github.com/ljharb/es-to-primitive/blob/master/es5.js#L11-L28, has the correct tests passing.

**Comment by Xotic750** [comment]
Thanks, I came across it when I started looking at using `uglify`'s `compress` option, it started throwing warnings. Happy New Year! :)
